version: '3'

volumes:
  db-data:
    driver: local

services:
    postgres:
      image: postgres:15.1-alpine
      container_name: mcsp-db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mcsp
      ports:
        - '5432:5432'
      volumes:
        - db-data:/var/lib/postgresql/data

