server:
  port: 8080
spring:
  application:
    name: doctors
  config:
    import: 'consul:'
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: doctors-i1
      config:
        data-key: data
        format: yaml
